# General
title:                "Statically"

# A simple tagline: Make it Static!
tagline:              >-
    A free multi-CDN for open source project, WordPress, images and more

# Define description for the site
description:          >-
    Statically is a free multi-CDN for open source project, WordPress, images and other assets with high-performance of caching and optimization.

# Also used for SEO Tag
logo:                 "/static/images/statically_wide.svg"
lang:                 "en_US"

# Set URL
url:                  "https://statically.io"

encoding:             "UTF-8"
permalink:            /:title
highlighter:          rouge
version:              1.0
year:                 2019

# Utilities
future:               true
jailed:               false
gfm_quirks:           paragraph_end

repo:                 "https://github.com/marsble/statically"

# Statically
statically:
    devs_url:         "https://developers.marsble.com"
    datacenter_num:   165+
    main_cdn:         "CloudFlare, Fastly, CDN77, and BunnyCDN"
    newsletter_url:  >-
        https://marsble.us18.list-manage.com/subscribe/post?u=4dfd4ae04677bf4f6248182fc&amp;id=397ea962f2

# Analytics
marsble:
    username:         statically
    analyticsDomain:  "pixel.marsble.com"
    analyticsId:      "2"

# Social
social:
    name:             "Statically"
    links:
      - https://marsble.com/u/statically
      - https://twitter.com/staticallyio
      - https://www.instagram.com/staticallyio
      - https://github.com/marsble

# Twitter
twitter:
    username:         staticallyio

# Instagram
instagram:
    username:         statically

# GitHub
github_username:      marsble

# The author
author:
    twitter:          fransallen

# Static files
cdn:
    domain:           "cdn.statically.io"
    url:              "https://cdn.statically.io"
    imgpx_domain:     "cdn.statically.io/img"
    imgpx_url:        "https://cdn.statically.io/img"
    favicons_domain:  "cdn.statically.io/favicons"
    favicons_url:     "https://cdn.statically.io/favicons"
    badge_domain:     "cdn.statically.io/badges"
    badge_url:        "https://cdn.statically.io/badges"
    static:           "/static"

sass:
    sass_dir:         "./static/css"
    style:            compressed

# Include to public directory
include:
    - "_headers"
    - "_pages"
    - "_redirects"
    - "_redirections"

kramdown:
    input:            GFM
    hard_wrap:        false

# Jekyll minifier config
jekyll-minifier:
  exclude: 'static/js/app.js'

# Plugins
plugins:
    - jekyll-seo-tag
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-minifier
